### ISSUE TITLE
正常听歌，IP让封了，怎么办

### ISSUE THREAD

**Issue by CBD6666** [Huibq/keep-alive#2]
正常听歌，IP让封了，怎么办

**Comment by Huibq** [comment]
> 正常听歌，IP让封了，怎么办

加群组反馈：https://t.me/+Xh7BWUUPqUZlMDU1

**Comment by CBD6666** [comment]
找到原因了，因为那会断网了，然后一直切换音乐，ip被封了，被封后该怎么办啊

**Comment by CBD6666** [comment]
找到原因了，因为断网一直换歌被封了，现在该怎么办才能解除啊

**Comment by Huibq** [comment]
> 找到原因了，因为断网一直换歌被封了，现在该怎么办才能解除啊

向这个邮箱发被封禁的IP：wcisman8@outlook.com

**Comment by CBD6666** [comment]
好的，大佬，那个群组是tg吗
